### ISSUE TITLE
Unable to assign nested environments to VPC configured at parent BG

### ISSUE THREAD

**Issue by mulesoft-mike** [mulesoft-consulting/terraform-provider-anypoint#23]
When creating a child business group from the parent, and assigning a VPC at the parent, I'm unable to define a list of environments associated to the VPC. 

If you first run:

> resource "anypoint_bg" "mike_corp_bg" {
>   name = "MikeCorp"
>   parentorganizationid = var.parent_org
>   ownerid = var.owner_id
>   entitlements_createsuborgs = true
>   entitlements_createenvironments = true
>   entitlements_globaldeployment = true
>   entitlements_vcoresproduction_assigned = 0
>   entitlements_vcoressandbox_assigned = 0.1
>   entitlements_vcoresdesign_assigned = 0
>   entitlements_staticips_assigned = 0
>   entitlements_vpcs_assigned = 0
>   entitlements_loadbalancer_assigned = 0
>   entitlements_vpns_assigned = 0
> }
> 
> resource "anypoint_env" "sandbox_environments" {
>   count = length(var.sandbox_environments)
>   org_id = anypoint_bg.mike_corp_bg.id
>   name = element(var.sandbox_environments, count.index)
>   type = "sandbox"
> }
> 
> resource "anypoint_env" "production_environments" {
>   count = length(var.production_environments)
>   org_id = anypoint_bg.mike_corp_bg.id
>   name = element(var.production_environments, count.index)
>   type = "production"
> }
> 
> resource anypoint_vpc "production_vpc" {
>     cidr_block = "10.0.0.0/16"
>     name = "MikeCorp_PROD_VPC"
>     org_id = var.parent_org
>     region = var.regions["eu-west-1"]
> //    shared_with = tolist([anypoint_bg.mike_corp_bg.id])
> //    associated_environments = anypoint_env.production_environments[*].id
> }
> 
> resource anypoint_vpc "sandbox_vpc" {
>     cidr_block = "10.0.0.0/16"
>     name = "MikeCorp_NON_PROD_VPC"
>     org_id = var.parent_org
>     region = var.regions["eu-west-1"]
> //    shared_with = tolist([anypoint_bg.mike_corp_bg.id])
> //    associated_environments = anypoint_env.sandbox_environments[*].id
> }

 Then uncomment shared_with, and re apply then the VPC is shared with the child, but linking the environments fails

> │ Error: Unable to Create VPC
> │ 
> │   on resources.tf line 31, in resource "anypoint_vpc" "production_vpc":
> │   31: resource anypoint_vpc "production_vpc" {
> │ 
> │ {"status":400,"message":"Not all of the environments: [8257eeb4-936a-42b2-97e0-508f7b272968] are in the organization or in sub-organization structure."}
> ╵
> ╷
> │ Error: Unable to Create VPC
> │ 
> │   on resources.tf line 40, in resource "anypoint_vpc" "sandbox_vpc":
> │   40: resource anypoint_vpc "sandbox_vpc" {
> │ 
> │ {"status":400,"message":"Not all of the environments: [f65e3a7b-73cc-4c94-90ec-e4a65a041e8b, 1be05145-04da-4c5e-9c47-02b2f4a4ee3b, d6150798-84f5-44dd-b41a-3e480c2e234c] are in the
> │ organization or in sub-organization structure."}

If you try and run the whole script as one then the error is around the VPC and not the environments

> ╷
> │ Error: Unable to Create VPC
> │ 
> │   on resources.tf line 31, in resource "anypoint_vpc" "production_vpc":
> │   31: resource anypoint_vpc "production_vpc" {
> │ 
> │ {"status":400,"message":"The list of organizations: [5faad559-9c48-4a3d-a1d7-edf5676d6173] is not in the sub-organization tree."}
> ╵
> ╷
> │ Error: Unable to Create VPC
> │ 
> │   on resources.tf line 40, in resource "anypoint_vpc" "sandbox_vpc":
> │   40: resource anypoint_vpc "sandbox_vpc" {
> │ 
> │ {"status":400,"message":"The list of organizations: [5faad559-9c48-4a3d-a1d7-edf5676d6173] is not in the sub-organization tree."}

It seems like there's a dependency on resources creating before the response is returned, and maybe the data is not set when trying to create the VPC/Environment.

I'm also using a variables file:

> variable username {
>   type        = string
>   default     = "mike_cat"
>   description = "the username of the anypoint user"
> }
> 
> variable password {
>   type        = string
>   sensitive   = true
>   description = "the password of the anypoint user"
> }
> 
> variable sandbox_environments {
>   description = "Sandbox/Non Production Environments List"
>   type        = list
>   default     = ["dev","qa", "uat"]
> }
> 
> variable production_environments {
>   description = "Production Environments List"
>   type        = list
>   default     = ["pro"]
> }
> 
> variable "regions" {
>   type = map
>   default = {
>     "eu-west-1"  = "eu-west-1"
>   }
> }
> 
> variable owner_id {
>   type        = string
>   default     = "4ba9236f-fc97-49d1-b90c-c86dee1c6e13"
>   description = "the id associated with mike-cat"
> }
> 
> variable parent_org {
>   type        = string
>   default     = "aa1f55d6-213d-4f60-845c-207286484cd1"
>   description = "The Parent Org"
> }

To run this update your username to yours, and export TF_VAR_password={your-password} so Terraform takes your password from your environment variable

**Comment by arun-tu** [comment]
Try to get environments as below and see if you can variables them.
https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/minor/1.0/console/method/%235714/
