### ISSUE TITLE
Standardise naming conventions to use underscores and make fields match across resources

### ISSUE THREAD

**Issue by mulesoft-mike** [mulesoft-consulting/terraform-provider-anypoint#27]
I noticed that the bg resource uses different standards compared to the rest of the resources.

`parentorganizationid` instead of `parent_organization_id`
`ownerid` instead of `owner_id`
`isproduction` instead of `is_production`
`organizationid` instead of `org_id`  (this is for environment as a nested schema)

**Comment by soufi** [comment]
PR created. 
Waiting to validate this 
Will be included for release v1.1.0
