### ISSUE TITLE
DLB certificates issue after initial apply

### ISSUE THREAD

**Issue by ccortinhas-pmi** [mulesoft-consulting/terraform-provider-anypoint#39]
Hi guys,

I encountered an issue where after successfully deploying a DLB with certificates, every subsequent `terraform plan/apply` will re-apply the ssl_endpoints settings despite no changes were made.

The following code reproduces the issue:

```terraform
resource "anypoint_dlb" "dlb" {
  org_id = var.bg_id
  vpc_id = "vpc-XXXXXXXXXXXXX"
  name = "sample-dlb"
  state = "started"
  ip_whitelist = ["0.0.0.0/0"]
  http_mode = "off"
  tlsv1 = false
  ssl_endpoints {
    public_key_label = "tf-public-key-name"
    public_key = ""
    private_key_label = "tf-private-key-name"
    private_key = ""
    verify_client_mode = "off"
    mappings {
      input_uri = "{app}/"
      app_name = "{app}"
      app_uri = "/" 
    }
  }
}
```

Additionally every subsequent plan/apply also detects a drift in `state`: `~ state                = "STARTED" -> "started"`. This one seems to be just a case-sensitive matter.

**Comment by RamziChoueri2903** [comment]
Can someone pick this up, please? I see that issue as major adoption obstacle for our customers?

Ramzi Choueri
MuleSoft

**Comment by RamziChoueri2903** [comment]
@soufi as discussed

**Comment by soufi** [comment]
Hi @ccortinhas-pmi, 
This issue is related to the following [issue](https://github.com/hashicorp/terraform-plugin-sdk/issues/477) on Terraform. 

It is very tricky to handle list-type attributes diff. I'm trying to find a way where the DLB current structure wouldn't be affected. Any suggestions are welcome.
