### ISSUE TITLE
Unable to create a VPC with an Internet VPC route

### ISSUE THREAD

**Issue by ccortinhas-pmi** [mulesoft-consulting/terraform-provider-anypoint#40]
I will use this issue to report two related situations, please tell me if you would prefer me to divide this into two separate github issues.

**Scenario 1**

When I try to create a VPC using the following code:

```terraform
resource "anypoint_vpc" "avpc" {
  owner_id                     = var.bg_id
  org_id                       = var.bg_id
  name                         = "test-issue-vpc"
  region                       = "eu-west-1"
  cidr_block                   = var.vpc_cidr_block
  is_default                   = false
  shared_with                  = []
  internal_dns_servers         = []
  internal_dns_special_domains = []

  vpc_routes {
    cidr = "0.0.0.0/0"
    next_hop = "Internet Gateway"
  }
}
```

This code will simply crash the plugin and the VPC doesn't get created. 

**Scenario 2**

If I remove the `vpc_routes` code block
```terraform

resource "anypoint_vpc" "avpc" {
  owner_id                     = var.bg_id
  org_id                       = var.bg_id
  name                         = "test-issue-vpc"
  region                       = "eu-west-1"
  cidr_block                   = var.vpc_cidr_block
  is_default                   = false
  shared_with                  = []
  internal_dns_servers         = []
  internal_dns_special_domains = []
}
```
 
The VPC gets created successfully. However, every subsequent `terraform plan/apply` to this same code will identify a drift:

```log
      - firewall_rules {
          - cidr_block = "100.100.100.0/19" -> null
          - from_port  = 8091 -> null
          - protocol   = "tcp" -> null
          - to_port    = 8092 -> null
        }
      - firewall_rules {
          - cidr_block = "0.0.0.0/0" -> null
          - from_port  = 8081 -> null
          - protocol   = "tcp" -> null
          - to_port    = 8082 -> null
        }

      - vpc_routes {
          - cidr     = "100.100.100.0/19" -> null
          - next_hop = "Local" -> null
        }
      - vpc_routes {
          - cidr     = "0.0.0.0/0" -> null
          - next_hop = "Internet Gateway" -> null
        }
```

The assumption is that the VPC creates automatically two VPC Routes and two firewall rules, however and since they are not in the terraform file, it will always try (and fail) to remove those settings.

Our solution for this is not ideal, we're adding these fields to the `ignore_changes` list and managing them manually, it would be great to be able to manage both `vpc_routes` and `firewall_rules` from terraform.

cc: @rubycube @RamziChoueri2903 @pmi-snmiguel

**Comment by RamziChoueri2903** [comment]
@soufi as discussed

**Comment by soufi** [comment]
Hi @ccortinhas-pmi

It's actually odd because I use vpc routes on my playground. Here's an example I've been running: 

```terraform
resource "anypoint_vpc" "avpc" {
  org_id = anypoint_bg.bg.id
  name = "myAwesomeVPC"
  region = "us-east-2"
  owner_id = anypoint_bg.bg.id
  cidr_block = "192.168.0.0/24"
  internal_dns_servers = []
  internal_dns_special_domains = []
  is_default = true
  associated_environments = []
  shared_with = []
  firewall_rules {
    cidr_block = "0.0.0.0/0"
    from_port = 8081
    protocol = "tcp"
    to_port = 8082
  }
  firewall_rules {
      cidr_block = "10.0.0.0/20"
      from_port = 8091
      protocol = "tcp"
      to_port = 8092
  }
  vpc_routes {
    cidr = "10.0.0.0/20"
    next_hop = "Local"
  }
  vpc_routes{
    cidr = "0.0.0.0/0"
    next_hop = "Internet Gateway"
  }
}
```

**Comment by ccortinhas-pmi** [comment]
Hello @soufi 

And are you able to create a VPC from start with the internet gateway VPC route already defined? We get a plugin crash each time.. And that is why we removed those fields since they are created in the background anyway.

I would love to run a few more examples on my side but sadly we reached the VPC limit in Anypoint, as soon as I manage to do it I'll provide more info about my setup, including terraform version, plugin version (should be the latest though) and a complete execution log.

**Comment by arun-tu** [comment]
Hi @soufi , As you already created VPC. You can try to do terraform plan second time, you will see few more changes though you never make any changes to vpc.tf. I even faced similar issue. 
As a workaround, added below 
lifecycle {
    ignore_changes = all
  }

**Comment by rforte-mule** [comment]
Hi @arun-tu, @ccortinhas-pmi and @soufi,

As far as I understood, vpc_routes are Computed, they cannot be changed: https://help.mulesoft.com/s/article/How-to-View-the-VPC-Route-Table-using-the-API.

About the Firewall rules issue, I've created a specific diff method. Changes in Firewall rules are now correctly detected.

Fixes will be available in the next release.
