### ISSUE TITLE
Request: Allow setting Upstream TLS 1.2 in DLBs

### ISSUE THREAD

**Issue by ccortinhas-pmi** [mulesoft-consulting/terraform-provider-anypoint#42]
At this point in time and according to the docs:

https://registry.terraform.io/providers/mulesoft-anypoint/anypoint/latest/docs/resources/dlb

Upstream TLS 1.2 (**_upstream_tlsv12 (Boolean)_**) is a read-only value. Would it be possible to set it up via terraform sometime in the future?

Thanks

cc: @rubycube @RamziChoueri2903 @pmi-snmiguel

**Comment by RamziChoueri2903** [comment]
@soufi as discussed

**Comment by soufi** [comment]
Hi, This will be carried along with the issue #38
