### ISSUE TITLE
can we create tag: latest instead of hardcoding version

### ISSUE THREAD

**Issue by arun-tu** [mulesoft-consulting/terraform-provider-anypoint#58]
Hi,
Is there any way you can find a way to have 'latest' tag for version instead of number.

So we don't need to worry about latest versions

    anypoint = {
      source = "mulesoft-anypoint/anypoint"
      version = "latest"
    }

**Comment by soufi** [comment]
Hi @arun-tu, 

After thinking about this, I don't think we are ready to use the `latest` tag just yet. Using hardcoded version gives our users the ability to revert back to their original version in case of a bug or inconsistency in newer versions ...
