### ISSUE TITLE
[Feature Request] Runtime Manager Alerts?

### ISSUE THREAD

**Issue by rrrix** [mulesoft-consulting/terraform-provider-anypoint#59]
Hi! 

I just found this repo and I'm excited to use it. As an Operations Engineer one of the first things I looked for was being able to use this Terraform Provider to manage my Runtime Manager Alerts, of which I have quite a few that I've _manually_ built-out, but would love to codify them as Terraform. 

I see the underlying library already has support - https://github.com/mulesoft-consulting/anypoint-automation-client-generator/blob/master/spec/rm_alerts.yml 

Is this feature already planned?

If not, I may be able to work on a PR to add it (assuming you're accepting PRs?)

Thanks for the awesome provider!

**Comment by soufi** [comment]
Hi @rrrix, 

Thank you for your interest in this project ! 

So about alerts: we have created the AOS spec. and the library is generated [here](https://github.com/mulesoft-consulting/anypoint-client-go) I need to release it before you'll be able to use. 

We do accept PRs !! please join our new discord server: https://discord.gg/ApZBgfeY

**Comment by soufi** [comment]
Hi @rrrix 

I just released the initial version for runtime manager alerts [here](https://github.com/mulesoft-consulting/anypoint-client-go/releases/tag/rm_alerts%2Fv0.0.1)

You can use it to build the Runtime Manager Alerts and send a PR. please fork from the `dev` branch to start your development. 

Join us on discord if you wish to discuss and if you need any support :) 

Thank you !
