### ISSUE TITLE
VPN Resource

### ISSUE THREAD

**Issue by arun-tu** [mulesoft-consulting/terraform-provider-anypoint#61]
Hi,
I would like to request new resource, vpn config with tf.

Cloudhub api
https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/minor/1.0/console/method/%234889/

**Comment by soufi** [comment]
Hi @arun-tu, 

The VPN resource was release with the v1.3.0. 

Check out this [link](https://registry.terraform.io/providers/mulesoft-anypoint/anypoint/latest/docs/resources/vpn)
