### ISSUE TITLE
Bug 1.3

### ISSUE THREAD

**Issue by arun-tu** [mulesoft-consulting/terraform-provider-anypoint#62]
I had upgraded to latest version 1.13. When i try to install DLB ...its complaining that 
{"status":400,"message":"invalid private key format (PEM expected)"}

But when i revert to 1.2 it works perfectly. 

Can you please check.

**Comment by soufi** [comment]
Hi @arun-tu,
We will take a look on this one

**Comment by arun-tu** [comment]
DLB is already created with 1.12 and after changing the version above is the issue faced.

**Comment by soufi** [comment]
@arun-tu 
Can you please provide your script ? 
Thank you,

**Comment by arun-tu** [comment]
You can close this, i added lifecycle {
    ignore_changes = all
}
