### ISSUE TITLE
Group mappings getting replace on every plan/apply executing

### ISSUE THREAD

**Issue by munozmi** [mulesoft-consulting/terraform-provider-anypoint#66]
When executing a plan or apply, group mappings are getting replaced every time regardless of changes to csv template or inputs.  Using terraform 1.3.3

`Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # anypoint_team_group_mappings.lvl1_team_group_mappings[0] will be updated in-place
  ~ resource "anypoint_team_group_mappings" "lvl1_team_group_mappings" {
        id      = "98ebd64c-1bcb-4654-ae1a-6bd719df9422_a7e0e3f1-8231-441d-955a-f89541d977b2_groupmappings"
        # (3 unchanged attributes hidden)

      ~ groupmappings {
          - provider_id         = "76489936-63d0-4693-8667-a2319c16ce21" -> null
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.`

**Comment by soufi** [comment]
This is was solved in the latest commit to dev.
