### ISSUE TITLE
Error message when teams and teams roles csv files are empty

### ISSUE THREAD

**Issue by munozmi** [mulesoft-consulting/terraform-provider-anypoint#69]
When the teams and teams roles csv files are empty the following error messages is show.
To reproduce remove all team names and team roles from their respective csv files.

` Error: Insufficient roles blocks
│
│   on resources.tf line 60, in resource "anypoint_team_roles" "lvl1_teams_roles":
│   60: resource "anypoint_team_roles" "lvl1_teams_roles" {
│
│ At least 1 "roles" blocks are required.`

**Comment by soufi** [comment]
this issue is related to the template and therefore should not be opened here. closing this one
