### ISSUE TITLE
Team role error when no team specified

### ISSUE THREAD

**Issue by munozmi** [mulesoft-consulting/terraform-provider-anypoint#71]
When the teams.csv file is empty or no teams are being added the following error is always shown
```
╷
│ Error: Insufficient roles blocks
│ 
│   on resources.tf line 85, in resource "anypoint_team_roles" "lvl1_teams_roles":
│   85: resource "anypoint_team_roles" "lvl1_teams_roles" {
│ 
│ At least 1 "roles" blocks are required.
```
To reproduce leave teams_lvl1.csv empty and run terraform plan.

**Comment by soufi** [comment]
Hi @munozmi, 

Those issues are related to the templates not the provider itself... please open an issue on the templates repository instead. Thank you
