### ISSUE TITLE
Provider crashes with latest changes

### ISSUE THREAD

**Issue by munozmi** [mulesoft-consulting/terraform-provider-anypoint#72]
Getting this error after getting the latest commit.
Build of Nov 10 did not have this issue. 

`╷
│ Error: Request cancelled
│
│   with data.anypoint_roles.roles[1],
│   on data.tf line 150, in data "anypoint_roles" "roles":
│  150: data "anypoint_roles" "roles" {
│
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.`

`Stack trace from the terraform-provider-anypoint.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xdc2f68]

goroutine 126 [running]:
github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint.dataSourceRolesRead({0x112b448, 0xc000634d20}, 0x265119a0108?, {0xfb3d60?, 0xc0001a3d40?})
        C:/Work/Workspace/CAT/terraform-provider-anypoint/anypoint/data_source_roles.go:147 +0x368
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00051a8c0, {0x112b480, 0xc00012e060}, 0xd?, {0xfb3d60, 0xc0001a3d40})
        C:/Users/miguel.munoz/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00051a8c0, {0x112b480, 0xc00012e060}, 0xc000263180, {0xfb3d60, 0xc0001a3d40})
        C:/Users/miguel.munoz/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0005b2000, {0x112b3d8?, 0xc0001f1300?}, 0xc000388de0)
        C:/Users/miguel.munoz/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0005be000, {0x112b480?, 0xc0007b1a70?}, 0xc0007248c0)
        C:/Users/miguel.munoz/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:657 +0x41d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xf9db40?, 0xc0005be000}, {0x112b480, 0xc0007b1a70}, 0xc0006349c0, 0x0)
        C:/Users/miguel.munoz/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002aa700, {0x112eed8, 0xc0001a4340}, 0xc0002fb320, 0xc0005a02a0, 0x16c0f70, 0x0)
        C:/Users/miguel.munoz/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfe
google.golang.org/grpc.(*Server).handleStream(0xc0002aa700, {0x112eed8, 0xc0001a4340}, 0xc0002fb320, 0x0)
        C:/Users/miguel.munoz/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        C:/Users/miguel.munoz/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        C:/Users/miguel.munoz/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

Error: The terraform-provider-anypoint.exe plugin crashed!`

**Comment by rforte-mule** [comment]
Hi @munozmi, can you provide us with one or more resource examples?

**Comment by munozmi** [comment]
@rforte-mule  Managed to narrow it down to only affecting gov control plane. 
Running a terraform plan on my own org, which is in the US plan doesn't produce the error.  
On the other hand, running a terraform plan on gov cloud I've managed to reproduce it. 

The error seems to happen when it's fetching the team roles.
![image](https://user-images.githubusercontent.com/104148456/209150189-d419ba82-8aac-4c4d-92ca-36face61f406.png)

**Comment by munozmi** [comment]
After last merge a few module version got reverted to previous values.  I suspect this is the root cause.
![image](https://user-images.githubusercontent.com/104148456/209202736-03b2d10a-93a0-4947-a9b7-2d7b6ba8e355.png)

**Comment by rforte-mule** [comment]
Yes, that was me. I'll fix it and let you know

**Comment by rforte-mule** [comment]
@munozmi Changes reverted; can you check, please?

**Comment by munozmi** [comment]
@rforte-mule Working now. Thanks!
