### ISSUE TITLE
Unable to add client certificate to a Load Balancer

### ISSUE THREAD

**Issue by ccortinhas-pmi** [mulesoft-consulting/terraform-provider-anypoint#83]
Using provider v1.5.2 we are deploying multiple DLBs with certificates. However we noticed that it is not possible to set a Client Certificate, for example of a trusted CA to verify client certificates. Can you implement this feature please? It's one of the few mandatory manual steps that's stopping us from fully automating our Mulesoft infrastructure.

**Comment by soufi** [comment]
Hi @ccortinhas-pmi, 

I am happy to help you with this, but I need you to  point me to the documentation about what exactly you're trying to accomplish with DLB or if you can send me a quick video of the steps you perform to do this. 

Discord: https://discord.gg/pSx9vaZ3

**Comment by ccortinhas-pmi** [comment]
Hello @soufi ,

A close case to ours is explained [here](https://help.mulesoft.com/s/article/How-to-handle-mixed-client-authentication-configuration-one-way-two-way-ssl-in-Dedicated-Load-Balancers).

Notice the second screen in particular and the client certificate:
![image](https://github.com/mulesoft-consulting/terraform-provider-anypoint/assets/83591746/520af691-4692-4291-be34-6350c08fb235)

We had success in setting the SSL/TLS certificate via terraform, but we also need to apply a client certificate, and it seems that anypoint provider v1.5.2 didn't support that yet, unless we overlooked something.

**Comment by soufi** [comment]
Thank you @ccortinhas-pmi I will take a look at this as soon as possible. You are welcome to help this is an open source initiative ;)

**Comment by soufi** [comment]
@ccortinhas-pmi  can you open a ticket on the fork : https://github.com/mulesoft-anypoint/terraform-provider-anypoint 

Thank you

**Comment by soufi** [comment]
you can close this one, it was solved on the v1.5.3 of the provider and PR was sent here for alignment.
